### ISSUE TITLE
Error Message: "Uncaught TypeError: Cannot read property to `toString` of undefined ..." on WebOS 4.4.2

### ISSUE THREAD

**Issue by lDeKul** [Cathwyler/MagicRemoteService#27]
Hi,

first i wanted to thank you for your latest Release with the Overlay Function. I really do appreciate it. With the Version 1.2.4.2, i am getting the attached Error Message.

My TV:

LG 43UK6470
WebOS 4.4.2-11
Firmware: 05.50.15
Board: LM18A

The TV is rooted.

![webos-dev-tmp-0ded2ec0-054d-4e4b-9432-a71ae61849fd](https://github.com/Cathwyler/MagicRemoteService/assets/152601437/c5eba760-ac09-466c-936c-1c7af8991e3d)

Thank you again...

BTW:

If you have any Ideas on how to solve this Problem, you can tell me what to do or try, too. Given that my TV is rooted, i can make changes directly in the App Files on the TV. Any Ideas or Help would be greatly appreciated.

I did not have this Problem with the last Release. I am going to try it without the "Overlay" Option to find out if the error still occurs.

**Comment by Cathwyler** [comment]
Unfortunately, the error message is not giving me helpful information.
I just fixed this message in the latest [release](https://github.com/Cathwyler/MagicRemoteService/releases)
This will not fix the bug but if you can send me the new message, it will help me to fix it.

**Comment by lDeKul** [comment]
Hi,
i have installed your newest Release. Both on PC and TV.

Now i get the following:

Log
Failed to close[]

Everything still continues to work fine. Its just the Message that Appears. The good thing in this Version is, that i can get rid of the message by a simple left Button press. Or Remote press.

![webos-dev-tmp-214c7a48-d9d3-4b93-8b21-723aece79a7e](https://github.com/Cathwyler/MagicRemoteService/assets/152601437/a2cb9c6c-ca6c-43ff-9116-6a4188a40fcd)

**Comment by Cathwyler** [comment]
Did you build the app by yourself from CLI or did you use the install on TV button ?

**Comment by lDeKul** [comment]
I installed it via the "Install on TV" Button.
I even tried installing it via webOSdevManager.

When i change Apps from MagicMouse HDMI to LiveTV and back to MagicMouse HDMI then it does not work. The Screen stays at Live TV. I need to kill the App by pressing the Back Button and then start it again for it to work.

Sometimes if i change from MagicMouse HDMI to YouTube, i can not navigate in Youtube. Again i need to press the Back Button shortly, for the Navigation in Youtube to work.

Is it possible that its kinda stuck in overlay?

Anyway, with your newest Release the Error is almost completely gone (maybe 1 or 2 times an Hour) and i can just click it away. If i am the only one with this Problem, i really would not want you to waste to much time with this.

If you need any more Infos please don't hesitate to ask. I don't have a Problem with Beta Testing Stuff either.

Btw: I am using a Laptop. And Sometimes i close the Lid, with the Laptop still being on and in use over the TV. I did try out a lot of things but it seems unrelated, but maybe that is the Reason for it.

I truly don't believe its worth putting to much effort into this if i am pretty much the only one who has this issue.

Thank you again for everything.

**Comment by Cathwyler** [comment]
Hi,

Thanks for all these informations. it confirms that the service reponsible of stopping and starting the overlay was not working on your webOS version.

The error message now works but some information is still missing. I fixed the service error message and a probable service bug in the latest release.

Can you give a new try and tell me if it's working or else send me the new error message ?

**Comment by lDeKul** [comment]
Thank you for your quick answer. I installed the new Version. You can find the error Message attached. At the same time, syslog shows the following:

**`[12:51:23.046][WARNING] ls-hubd LSHUB_NO_SERVICE _LSHubSendQueryNameReplyMessage: Failed Connecting to Service err_code: -3, service_name: "com.cathwyler.magicremoteservice.hdmi3.send", unique_name: "(null)", static, fd -1 {}`**

![webos-dev-tmp-9f9f2f27-ac1c-49a2-b98a-ea86d2d57dd4](https://github.com/Cathwyler/MagicRemoteService/assets/152601437/4e14df9d-5d20-4ce7-8616-1f3994c17190)


[syslog.txt](https://github.com/Cathwyler/MagicRemoteService/files/14550023/syslog.txt)

Thank You very much. Your Support is greatly appreciated. Have a nice Sunday..

**Comment by Cathwyler** [comment]
I just found a possible explanation in the official webOS documentation https://webostv.developer.lge.com/develop/guides/js-service-basics#supported-nodejs-version
I was not aware that some basic commands are not available in Node.js version used in webOS 4.x or lower version.

Can you give a new try if you have some time left ?

**Comment by lDeKul** [comment]
Of course.

I just installed it and will give you an Update, shortly.

I can't thank you enough for taking the time and putting in all this effort.

Thanks a lot..

**Comment by lDeKul** [comment]
Unfortunately i get an Error Message again.

![webos-dev-tmp-2b3656b7-b051-4b47-b61f-4cd9180afae2](https://github.com/Cathwyler/MagicRemoteService/assets/152601437/e6ce29c0-28b6-4e74-ba62-58f00e819684)

Please let me know if there is anything else i can do, to help. The TV is roote and i have terminal access.

Thanks again...

**Comment by Cathwyler** [comment]
I'm sure this bug is a stupid one but the problem is that i'm not able to reproduce it with webOS emulator.
Above that i'm not a Node.js specialist and i don't know actually how to debug it with older Node.js version.
On internet it seems there isn't log/error file.

Are you using Wake on Lan? Do you have an error message when you click on start button ? Do you have the same error message ?

i'm in vaccation next week but when i come back i will do some search to find a debug solution.
In the meantime, if anyone have any clue, I would gladly accept it.

**Comment by Cathwyler** [comment]
Hi,

I fixed a probable service bug on webOS 4.x and earlier running with older node.js version.

Can you give a new try with the latest release?

**Comment by lDeKul** [comment]
Hi,

that did it. The error Message is gone. And everything else seems to work just like before.

Thank You Very Much...

I really do appreciate it.

Thanks again for you hard work and this great tool.

DeKu
